name: wisata_rekreasi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  image_picker: ^1.1.2
  geolocator: ^14.0.1
  flutter_image_compress: ^2.4.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  intl: ^0.19.0
  flutter_advance_slider: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/location.png
    - assets/placeholder_image.png
    - assets/Lampung.jpg
    - assets/Bandung.jpg
    - assets/Bogor.jpg
    - assets/Denpasar.jpg
    - assets/Jakarta.jpg
    - assets/Jogja.jpg

  # fonts:
  #   - family: Nunito
  #     fonts:
  #       - asset: assets/Nunito-Regular.ttf