// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKvtVDI2XtyakGx7aAsnf_hVPd882I28k',
    appId: '1:891344825549:web:419b77cee53548c5e94d84',
    messagingSenderId: '891344825549',
    projectId: 'wisata-rekreasi',
    authDomain: 'wisata-rekreasi.firebaseapp.com',
    storageBucket: 'wisata-rekreasi.firebasestorage.app',
    measurementId: 'G-1NLC8GPYEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtjjqhnS-FJSt1dkIONzz61B3Zz1D3ik0',
    appId: '1:891344825549:android:0fb1bf1c25c62873e94d84',
    messagingSenderId: '891344825549',
    projectId: 'wisata-rekreasi',
    storageBucket: 'wisata-rekreasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmDBhKnYp6HWOj8pxOC_mtXDx91nl_aHA',
    appId: '1:891344825549:ios:33131de4549ffcbee94d84',
    messagingSenderId: '891344825549',
    projectId: 'wisata-rekreasi',
    storageBucket: 'wisata-rekreasi.firebasestorage.app',
    iosBundleId: 'com.example.wisataRekreasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmDBhKnYp6HWOj8pxOC_mtXDx91nl_aHA',
    appId: '1:891344825549:ios:33131de4549ffcbee94d84',
    messagingSenderId: '891344825549',
    projectId: 'wisata-rekreasi',
    storageBucket: 'wisata-rekreasi.firebasestorage.app',
    iosBundleId: 'com.example.wisataRekreasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKvtVDI2XtyakGx7aAsnf_hVPd882I28k',
    appId: '1:891344825549:web:3d761e8bda3c74e1e94d84',
    messagingSenderId: '891344825549',
    projectId: 'wisata-rekreasi',
    authDomain: 'wisata-rekreasi.firebaseapp.com',
    storageBucket: 'wisata-rekreasi.firebasestorage.app',
    measurementId: 'G-4GBBHJWXJQ',
  );
}
